version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Etc/UCT
  ignore:
  - dependency-name: mocha
    versions:
    - ">= 8.0.a, < 8.1"
  - dependency-name: mocha
    versions:
    - ">= 8.2.a, < 8.3"
  - dependency-name: "@types/mocha"
    versions:
    - ">= 8.0.a, < 8.1"
  - dependency-name: "@types/mocha"
    versions:
    - ">= 8.2.a, < 8.3"
  - dependency-name: ajv
    versions:
    - 7.0.3
    - 7.0.4
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 7.2.3
    - 7.2.4
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.5
    - 8.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@xml-tools/ast"
    versions:
    - 5.0.3
  - dependency-name: "@xml-tools/parser"
    versions:
    - 1.0.9
