name: Lint without auto fix

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - feat/switch-to-github-actions
  pull_request:
    branches:
      - master
      - feat/switch-to-github-actions

jobs:
  run-linters:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: run ci # will run `yarn run ci` command
      # - name: Run lint:fix
      #   run: pnpm run lint:fix
      # - name: Commit lint fixes if any
      #   run: |
      #           git config --global user.name github-actions[bot]
      #           git config --global user.email github-actions[bot]@users.noreply.github.com
      #           git add pnpm-lock.yaml
      #           git commit -m "Linting auto fix commit" -a --no-verify || true
      #           git push  || true
